### ISSUE TITLE
[BUG]: TypeError: __init__() missing 1 required positional argument: 'bounds'

### ISSUE THREAD

**Issue by OlutokiJohn** [thieu1995/IntelELM#3]
### Description of the bug

when i try fitting the MhaElmRegressor model i keep gettinto this error `TypeError: __init__() missing 1 required positional argument: 'bounds'`
"

### Steps To Reproduce

opt_paras = {"name": "GA", "epoch": 10, "pop_size": 30}
regressor = MhaElmRegressor(hidden_size=10, act_name="elu", obj_name="RMSE", optimizer="BaseGA", optimizer_paras=opt_paras)
regressor.fit(X_train_scaled, y_train)

**Comment by thieu1995** [comment]
Can you try:

pip install mealpy==2.5.4

**Comment by OlutokiJohn** [comment]
still same problem

**Comment by thieu1995** [comment]
sorry. I forgot, this is latest version, so you actually need latest version of mealpy.

pip install mealpy==3.0.1

If the problem is still there, can you post the code you define the Problem dictionary?
