### ISSUE TITLE
[FEAT]: Best solution ( Best parameter value)

### ISSUE THREAD

**Issue by syyd87** [thieu1995/IntelELM#4]
### Description

I want to know how to get the best parameter value that has been optimized by the metaheuristic model. Can you give an example?

Thanks

### Additional Information

For example in mealpy; print(f"Best agent: {model.g_best}")
print(f"Best solution: {model.g_best.solution}")
print(f"Best accuracy: {model.g_best.target.fitness}")
print(f"Best parameters: {model.problem.decode_solution(model.g_best.solution)}")

**Comment by thieu1995** [comment]
Hi @syyd87 ,

You can get it from here:
https://github.com/thieu1995/IntelELM/blob/main/examples/utils/exam_get_weights.py

**Comment by syyd87** [comment]
Thanks for your information
